#!/bin/sh
echo "Generating at" `date` >> build-wc-tapes.log
mkdir -p ~/tmp/tapes-wc-2gram/
mkdir -p ~/tmp/tapes-wc-3gram/
mkdir -p ~/tmp/tapes-wc-4gram/
mkdir -p ~/tmp/tapes-wc-5gram/
time zcat ~/ngrams/data/2gms/*.gz | ./judysort-prepare-tapes -L 100000000 -T ../working/transformer.gz -W -n 2 -P ~/tmp/tapes-wc-2gram/ 2>> build-wc-tapes.log
time zcat ~/ngrams/data/3gms/*.gz | ./judysort-prepare-tapes -L 100000000 -T ../working/transformer.gz -W -n 3 -P ~/tmp/tapes-wc-3gram/ 2>> build-wc-tapes.log
time zcat ~/ngrams/data/4gms/*.gz | ./judysort-prepare-tapes -L 100000000 -T ../working/transformer.gz -W -n 4 -P ~/tmp/tapes-wc-4gram/ 2>> build-wc-tapes.log
time zcat ~/ngrams/data/5gms/*.gz | ./judysort-prepare-tapes -L 100000000 -T ../working/transformer.gz -W -n 5 -P ~/tmp/tapes-wc-5gram/ 2>> build-wc-tapes.log
echo "Done at" `date` >> build-wc-tapes.log
